### ISSUE TITLE
Falta descripción y foto

### ISSUE THREAD

**Issue by asanzo** [pdepjm/2021-kata0-prensentacion-Aldo991#1]
¡Hola @Aldo991 !

Te faltó subir descripción y foto. ¿Podemos ayudarte con algo?

Saludos!

**Comment by Aldo991** [comment]
Hola buenas, si colgué con la foto y la descripción, ya que cuando instale el Visual, Git y GHC creí que era todo, ahora dentro de un rato pongo la foto y la descripción, cualquier dificultad que tenga la pongo en los canales de discord.

**Comment by asanzo** [comment]
Redondo!
